# Generated by Django 5.2.17 on 2026-09-06 02:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NOOP', 'Teste'), ('SYNC_CNPJ_SOURCE', 'Sincronizar fonte CNPJ'), ('DISCOVER_CNPJ', 'Descobrir por CNPJ'), ('DISCOVER_MAPS', 'Descobrir no Maps'), ('ENRICH_MAPS', 'Enriquecer pelo Maps'), ('CRAWL_WEBSITE', 'Visitar website'), ('FIND_JOBS', 'Buscar vagas'), ('DETECT_SIGNALS', 'Detectar sinais'), ('CALCULATE_SCORE', 'Calcular score'), ('REFRESH_COMPANY', 'Atualizar empresa')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('RETRY_SCHEDULED', 'Nova tentativa agendada'), ('SUCCEEDED', 'Concluído'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('lock_owner', models.CharField(blank=True, max_length=120)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveBigIntegerField(default=0)),
                ('records_success', models.PositiveBigIntegerField(default=0)),
                ('records_failed', models.PositiveBigIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', 'run_after', 'created_at'),
                'indexes': [models.Index(fields=['status', 'run_after', 'priority'], name='job_claim_idx'), models.Index(fields=['type', 'created_at'], name='job_type_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('worker_id', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.job')),
            ],
            options={
                'ordering': ('attempt_number',),
                'constraints': [models.UniqueConstraint(fields=('job', 'attempt_number'), name='unique_job_attempt_number')],
            },
        ),
    ]
