# Generated by Django 5.2.17 on 2026-09-12 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_sourcecoverage_query_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(choices=[('INDUSTRY', 'Indústria'), ('PARTNER', 'Parceiro')], max_length=16)),
                ('product', models.CharField(blank=True, max_length=24)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('signal_types', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ('target', 'display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(choices=[('INDUSTRY', 'Indústria'), ('PARTNER', 'Parceiro')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cnae_prefixes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ('target', 'display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('ibge_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('receita_codes', models.JSONField(default=list)),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('immediate_code', models.CharField(max_length=8)),
                ('immediate_name', models.CharField(max_length=160)),
                ('intermediate_code', models.CharField(max_length=8)),
                ('intermediate_name', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ('state', 'name'),
            },
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('code', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('state_name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('COMMERCIAL', 'Região comercial'), ('IBGE_INTERMEDIATE', 'Região geográfica intermediária')], max_length=24)),
                ('source_version', models.CharField(max_length=80)),
                ('source_region_codes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('municipalities', models.ManyToManyField(related_name='regions', to='discovery.municipality')),
            ],
            options={
                'ordering': ('state', 'display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OpportunitySearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('target', models.CharField(choices=[('INDUSTRY', 'Indústria'), ('PARTNER', 'Parceiro')], max_length=16)),
                ('state', models.CharField(max_length=2)),
                ('technical_filters', models.JSONField(default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_searches', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_searches', to='discovery.initiative')),
                ('regions', models.ManyToManyField(blank=True, related_name='opportunity_searches', to='discovery.geographicregion')),
                ('segments', models.ManyToManyField(related_name='opportunity_searches', to='discovery.marketsegment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
